import Head from 'next/head'
import classes from './About.module.scss'

import { useRouter } from 'next/router'

import { useEffect } from "react"
import { useModal } from '../context/ModalContext'
import { EModalType } from '../enums/GeneralEnums'

const About = () => {
  const { query: { emailVerification, email } } = useRouter()
  const { dispatch: mDispatch } = useModal()

  useEffect(() => {
    if (!emailVerification || !email) return
    mDispatch({
      showModal: true,
      modalType: EModalType.Verify
    })
  }, [emailVerification, email])

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pern-Chat</h1>
      <h2>PostgreSQL, Express, React and Node</h2>
      <h3>This requires a login to use, but you can <a href='https://temp-mail.org'>create a temporary email</a> instead if you don&apos;t want to use your email address, OR just use one of the test accounts. The emails for the test accounts are test 1 to 6 @test.com and the password is Test1234!. The repository is also public on my github account. Everything gets deleted automatically after 20 minutes, including new accounts.</h3>
      <hr />
      <h4>You can create a chatroom or start a conversation with another user. You can also attach videos and images to messages. All images except attachment images update live using Pusher js. Click on a user inside a chatroom to start a direct conversation, or search for a user from the conversations section. Or you can create a post for the blog.</h4>
      <br />
      <div className={classes.lists}>
        <ul>
          <label>Features</label>
          <li>Image & Video attachments</li>
          <li>Live profile pictures</li>
          <li>Live room images</li>
          <li>Live comments</li>
          <li>Live chatrooms & messages</li>
          <li>Public static blog</li>
          <li>Upload progress bars</li>
          <li>Dark mode</li>
          <li>Google login</li>
          <li>Email verification</li>
          <li>API request body validation</li>
          <li>Rate limiting</li>
          <li>Custom image API route</li>
          <li>Mobile responsive layout</li>
        </ul>
        <ul>
          <label>Modules</label>
          <li>Amazon PostgreSQL RDS</li>
          <li>Cloudinary</li>
          <li>Next.js</li>
          <li>SASS</li>
          <li>Sharp.js</li>
          <li>Quill Editor</li>
          <li>Busboy</li>
          <li>Formik</li>
          <li>Yup</li>
          <li>Pusher.js</li>
          <li>Nodemailer</li>
          <li>Typescript</li>
          <li>Express-rate-limiter</li>
          <li>Express-slow-down</li>
        </ul>
      </div>
    </div>
  )
}

export default About
